<a href="https://colab.research.google.com/github/vinothkumarsevugan/vinothkumarsevugan/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [97]:
df=pd.read_csv("/content/50_Startups.csv")

In [98]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [99]:
df.count()

R&D Spend          50
Administration     50
Marketing Spend    50
State              50
Profit             50
dtype: int64

In [100]:
df.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [101]:
df.shape

(50, 5)

In [102]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [103]:
# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [104]:
X=X[:,1:]  #to qvoid dummy variable trap

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [106]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()    #reg is obhject
reg.fit(X_train,Y_train)

LinearRegression()

In [116]:
y_pred=reg.predict(X_test)

In [108]:
coeff_df = pd.DataFrame(reg.coef_, columns=['Coefficient'])

In [109]:
coeff_df

Coefficient
0  -959.284160
1   699.369053
2     0.773467
3     0.032885
4     0.036610

In [117]:
reg.intercept_  #C

42554.167617767

Next step to find the independant variable that has maximum support to output(dependant variable)

we will start with backward elimination
Building the optimal model using backward elimination

In [118]:
import statsmodels.formula.api as sm
X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)  #adding a number to start of the aray as we will use stats to check


yi = C + 1xi1 + 2xi2 + ... pxip  (C is associated with x0 and is equal to 1).

In [126]:
X

array([[1, 1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 1, 0.0, 1.0, 9

In [155]:
X_opt=X[:,1:7]

In [123]:
import statsmodels.api as sm

In [157]:
X_opt=X_opt.astype(float)

In [160]:
X_opt

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [147]:
# x_opt = np.array(X_opt, dtype=float) check with kousik as why one column was not added

In [161]:
rr=sm.OLS(endog=Y,exog=X_opt).fit()

In [162]:
rr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Fri, 27 May 2022   Prob (F-statistic):           1.34e-27
Time:                        18:54:16   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [164]:
X

array([[1, 1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 1, 0.0, 1.0, 9

In [166]:
X_opt=X[:,[1,4]]

In [167]:
X_opt=X_opt.astype(float)

In [168]:
rr=sm.OLS(endog=Y,exog=X_opt).fit()

In [169]:
rr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Fri, 27 May 2022   Prob (F-statistic):           3.50e-32
Time:                        19:04:37   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

R and D has the most importance 